### ISSUE TITLE
Test Driven Development with Dart/Flutter

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-flutter#42]
[TDD](https://github.com/dwyl/learn-tdd) allow us to think first of which features/functions we want to test.
We first write the test which will test a specific aspect of the application. At this stage the test will fail as there is nothing to test yet.
We then write the implementation to make the test pass and check that the test are working correctly. Once we know the test is valid we can refactor if necessary.
Finally we iterate this process with the other features of the application to arrive at a fully tested application.

Dart documentation for testing: https://dart.dev/guides/testing
Flutter documentation for testing: https://flutter.dev/docs/testing

## Tasks

+ [x] 1. **Learn** how to do TDD in Dart/Flutter following all the available tutorials.
  + [ ] Share _links_ to all the tutorials you find/follow
  + [ ] Include all the links in the "Relevant Reading" section at the end of `/tdd-example/README.md`
+ [ ] 2. Document the process of doing TDD with a complete _example_ that others can follow.
  Get inspiration from the existing @dwyl examples. e.g:
  + https://github.com/dwyl/learn-tdd#how
  + https://github.com/dwyl/learn-elm-architecture-in-javascript#how
  + https://github.com/dwyl/phoenix-chat-example#how

The example _must_:
+ [ ] Take the learner through building a basic app from scratch e.g. calculator or counter
+ [ ] create a new folder inside `learn-flutter` called `/tdd-example`
+ [ ] create a new flutter project with all the code.
+ [ ] inside the `/tdd-example` create `README.md` e.g: `/tdd-example/README.md` 
that will contain _step-by-step_ instructions for how to:
  + [ ] define the goal of the basic app that is being created.
  + [ ] write the test(s)
  + [ ] watch it _fail_
  + [ ] write the code to make the test pass.
  + [ ] include the screenshots of the device screen with the counter or calculator _working_.
 
+ [ ] 3. Finally, in the https://github.com/dwyl/learn-flutter#flutter-application-test which should be renamed just "Testing" you should _link_ to the `tdd-example` so that people can follow it to understand the basics of TDD/Testing in flutter.

**Comment by nelsonic** [comment]
@miguelmartins17 in the interest of keeping things clean (_this issue already has a large thread of comments that are unrelated to TDD in Flutter_), I have created https://github.com/dwyl/learn-flutter/issues/43 which has a _comprehensive_ checklist of what needs to be done to consider the "TDD in Flutter" to be complete. 
Please pick up the issue and work on it as your next task. 
Thanks. ☀️
