### ISSUE TITLE
TDD Flutter Example

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#43]
As a person wanting to build _reliable_ & _maintainable_ cross-platform native Apps in Flutter,
I want to learn the best practices of TDD from the start by following a great beginners example
so that I cultivate good habits for high quality tests and code.

We need to create a basic but _complete_ step-by-step example of doing TDD in Flutter with the _complete_ code on GitHub (_not just "snippets" or gists_) so that a _beginner_ can follow it from start to finish in less than an hour and _understand_ exactly **what** it takes to do TDD and ***how*** to do it.

## Todo/Tasks

+ [x] 1. **Learn** how to do TDD in Dart/Flutter following all the available tutorials.
  + [x] Share _links_ to all the tutorials you find/follow
  + [x] Include _all_ the links in the "Relevant Reading" section at the end of `/tdd-example/README.md`
  + Starting point: Dart: https://dart.dev/guides/testing & Flutter: https://flutter.dev/docs/testing
+ [x] 2. Document the process of doing TDD with a complete _example_ that others can follow.
  Get inspiration from the existing @dwyl examples. e.g:
  + https://github.com/dwyl/learn-tdd#how
  + https://github.com/dwyl/learn-elm-architecture-in-javascript#how
  + https://github.com/dwyl/phoenix-chat-example#how

The example _must_:
+ [x] Take the learner through building a basic app from scratch e.g. calculator or counter
+ [x] create a new repository https://github.com/dwyl/flutter-counter-example
+ [x] create a new flutter project 
  + [x] **git commit** the fresh project ***`before`*** you add any tests/code.
+ [x] inside the `/flutter-counter-example` create `README.md` file e.g: `/flutter-counter-example/README.md` 
  + [x] Structure the file the same way all our other tutorials are written to _answer_ the questions the reader is thinking "Why? What? Who? How?" 
  + [x] **Why?** define the goal of the basic app that is being created. 
  + [x] **What?** give a _brief_ (one sentence) description of what TDD is and What example app you are going to build.
    + [x] Link to the https://github.com/dwyl/learn-tdd tutorial that goes into more detail of "What" TDD is.
  + [x] **Who?**: who is this tutorial _for_? e.g: https://github.com/dwyl/elixir-auth-google#who-
  + [x] **How?** section should contain _step-by-step_ instructions for how to:
    + [x] **create** a **new flutter project** from scratch (_always create a **git commit** at the start of a project_)
    + [x] **write test**(s)
    + [x] **run tests** and watch them _fail_
    + [x] **write code** to make the test(s) _pass_.
    + [x] **`git commit`** the code at each stage so that the learner has a **_complete_ working example**.
    + [x] include the **screenshots** of the device screen with the counter or calculator _working_.
   
+ [x] 3. Finally, in the https://github.com/dwyl/learn-flutter#flutter-application-test which should be renamed just "Testing" you should _link_ to the `tdd-example` so that people can follow it to understand the basics of TDD/Testing in flutter. 

Writing this example does not need to take more than a couple of days of focussed effort.
But it will be a _superb_ resource for others. 

> @miguelmartins17 remember this is an _opportunity_ to _practice_ your skills and solidify the "basics" so that you have a good foundation to build on. The objective is to know the fundamentals so well that you can do them in your sleep. It's the same a basic fitness for performing a sport like Boxing. You don't expect to walk into the Boxing Ring and beat [Anthony Joshua](https://en.wikipedia.org/wiki/Anthony_Joshua) without any practice. The same way that you **_cannot_ possibly** expect to get a job as a developer without putting in _significant_ practice with the core skills; specifically Test Driven Development. [Technical Writing](https://en.wikipedia.org/wiki/Technical_writer) where you _explain_ things to other people in great detail is an _essential_ skill as a developer. It is a _strong_ differentiator between you and your peers. Trust me being able to [communicate](https://github.com/dwyl/apprenticeship#3-communication) effectively is every bit as important as being able to write code.

**Comment by miguelmartins17** [comment]
@nelsonic So first I should finish the Flutter TDD tutorial course, then move on to this issue?

**Comment by nelsonic** [comment]
Yeah, finishing the Flutter Clean Architecture and TDD course **notes** is _essential_. #15 📝 
https://github.com/dwyl/learn-flutter/blob/master/Flutter_TDD_Architecture_Course_notes.md 
At present the notes only go up to video **3**. There are 14 videos in the series. 📺

**Comment by miguelmartins17** [comment]
I've managed to make some progress. I just need to do the documentation.


![Tests_passing](https://user-images.githubusercontent.com/27420533/76870453-9f2f1200-6861-11ea-87c3-183cd744075a.png)

**Comment by nelsonic** [comment]
@miguelmartins17 _great_ that you are making progress! 🎉 

Please remember to `git add . && git commit -m 'describe your progress' && git push`
so that you are _recording_ your progress on a regular basis. 
(_ideally multiple times per day whenever you reach a checkpoint like a new section in the instructions_)
https://github.com/dwyl/flutter-counter-example
![last-commit-5-days-ago](https://user-images.githubusercontent.com/194400/76882222-3ef49c00-6872-11ea-91fa-739b2e8f2623.png)
The key to mastery is consistency. Push code each time you make an update. 
The _faster_ you make progress in _any/each_ task the faster you will reach your goals.

If you are facing obstacles, please _comment_ on the issue so we can help. 👍

**Comment by miguelmartins17** [comment]
@nelsonic I'm still trying to figure out how to add a function to the button.
I found it on StackOverflow. I'll try to use it.

https://stackoverflow.com/questions/51398531/how-to-give-onpressed-a-method-in-custom-button-flutter

**Comment by miguelmartins17** [comment]
Today I tried to run the application but when I tried to run it the following error appeared.
I already google it but I didn't get any solution.


![Screen Shot 2020-03-29 at 15 42 55](https://user-images.githubusercontent.com/27420533/77851977-08087980-71d4-11ea-891b-1eeae600cc1d.png)

**Comment by miguelmartins17** [comment]
@nelsonic These were the links where I tried to solve this problem.

- https://stackoverflow.com/questions/52421999/xcode-10-command-codesign-failed-with-a-nonzero-exit-code

- https://stackoverflow.com/questions/39652867/code-sign-error-in-macos-high-sierra-xcode-resource-fork-finder-information

- https://stackoverflow.com/questions/56616238/warning-for-xcode-capabilities-for-project-may-not-function-correctly-because

**Comment by nelsonic** [comment]
@nelsonic please get into the habit of pasting the `text` of the error into an issue screenshots are good for _context_ but they are useless for allowing anyone `else` to pick up the issue or _find_ the eventual solution via Googling.

**Comment by miguelmartins17** [comment]
This is the error written for the next one, I know I have to write.


```
Resource fork, Finder information, or similar detritus not allowed.
Command CodeSign failed with a nonzero exit code.
note: Using new build system.
note: Planning build
note: Constructing build description
Warning: capabilities for signing and capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this select a development team in the Runner editor.
```

**Comment by miguelmartins17** [comment]
I am currently following this post on StackOverflow.

https://stackoverflow.com/questions/39524148/xcode-error-code-signing-is-required-for-product-type-application-in-sdk-ios

**Comment by miguelmartins17** [comment]
This post talks about the error I have in Xcode build but it is still outdated in relation to the version.

https://www.twilio.com/blog/2018/07/how-to-test-your-ios-application-on-a-real-device.html

**Comment by miguelmartins17** [comment]
@nelsonic I was thinking that maybe the error that appears in Xcode build might be because it was outdated and then I saw that it had an update.
Every time I try to update, I get an email other than mine.



![Screen Shot 2020-04-02 at 10 44 45](https://user-images.githubusercontent.com/27420533/78235484-99c3ff80-74d0-11ea-9dea-4827a892d7fb.png)


How can I change the email address on the App Store so I can update Xcode? Is there another way to do this update other than from the App Store?

**Comment by nelsonic** [comment]
@miguelmartins17 the user on the Mac you are using was created specifically for you. You should not need to sign into _my_ iCloud account unless you are using a different user ... you are the "admin" on the machine so you can create a new user e.g "M2" and you should be able to start from scratch. It's actually a good test of the Learn Flutter installation instructions.
As for downloading XCode, sadly it's only possible through the App Store.

**Comment by miguelmartins17** [comment]
I am currently following this video:

https://www.youtube.com/watch?v=OtkrNQxJzBQ

**Comment by nelsonic** [comment]
Closing in favour of: https://github.com/dwyl/learn-flutter/issues/65
