### ISSUE TITLE
SPIKE: Make Basic REST API Request 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#6]
We will need to make API requests to our Phoenix Backend App in order to save data to the remote database. With that in mind we need to write a quick tutorial on how to make API requests in Flutter.

# Todo

+ [x] **Create** a new file in this repository called **`rest-api-tutorial.md`** and 
+ [x] **Capture** all the steps required to make a request to REST API
  > If you need an example of a basic tutorial for inspiration, see: [dwyl/learn-elm/tutorials/elm-ui](https://github.com/dwyl/learn-elm/tree/master/tutorials/elm-ui#how-)
+ [x] **Make** an **HTTP Request** to the Giphy API https://developers.giphy.com to 
+ [x] **Display a _random_ GIF** in a Flutter App.
  > You will need to obtain a Giphy API key (_or borrow the key from the [Elm example](https://github.com/dwyl/learn-elm/blob/e453fdd3dff50e17177bd8747c1716ca555c77e2/examples/http.elm#L90)_)
  > This is the example in Elm: https://elm-lang.org/examples/cat-gifs

## Potential useful links:

+ [x] Official docs: https://flutter.dev/docs/cookbook/networking/fetch-data
+ [x] Basic Tutorial: https://flutterawesome.com/how-to-integrate-rest-api-in-flutter
+ [x] Extended tutorial: https://www.tutorialspoint.com/flutter/flutter_accessing_rest_api.htm

If you have _any_ questions on any part of this, please ask by commenting below. 
If you are new to APIs or need a refresh/reminder, watch this video: https://github.com/dwyl/learn-api-design/issues/38

@miguelmartins17 in case you are wondering why this issue has the word "SPIKE" in the title,
see: https://en.wikipedia.org/wiki/Spike_(software_development) 😉

**Comment by miguelmartins17** [comment]
@nelsonic Working on this one right now 😎

**Comment by miguelmartins17** [comment]
Links that may be helpful in resolving this issue.

https://pub.dev/packages/giphy_picker

https://flutter.dev/docs/cookbook/networking/fetch-data

**Comment by miguelmartins17** [comment]
It is not possible to use the same API key as it was in elm because of an authentication error.



![Screen Shot 2020-02-13 at 20 55 49](https://user-images.githubusercontent.com/27420533/74477461-41468d80-4ea3-11ea-80a3-bc4f874d6b7c.png)

**Comment by nelsonic** [comment]
failure + persistence = progress. 😉

**Comment by miguelmartins17** [comment]
Of course I'll get a new API key from the site and keep going until I get it.

**Comment by miguelmartins17** [comment]
I've got a new API key now.

![Screen Shot 2020-02-14 at 08 19 09](https://user-images.githubusercontent.com/27420533/74513548-bb5a2f00-4f02-11ea-9c37-e9a19eb87c90.png)

**Comment by miguelmartins17** [comment]
This is the link that can help. When I have some progress I will comment here or in case I have more doubts I will open an issue.

https://stackoverflow.com/questions/53936739/how-to-control-gif-animation-in-flutter

**Comment by miguelmartins17** [comment]
@nelsonic I think the error was in using the API key. Where should I put ? Along with the link ?

**Comment by miguelmartins17** [comment]
@nelsonic I was looking at the example they did on elm but I can't figure out one thing where the API key is ?

**Comment by nelsonic** [comment]
@miguelmartins17 we need to investigate how to use Environment Variables in Dart/Flutter. That way you can include the API key in your app but **_not_ hard-code it**. see: https://github.com/dwyl/learn-environment-variables/issues/20

**Comment by miguelmartins17** [comment]
@nelsonic I think I've now reached the point where I need help I haven't been able to get the random gifs to work

**Comment by nelsonic** [comment]
Ok. In a comment _here_ on GitHub, _describe_ what you are trying to achieve in as much detail as possible and exactly what you have already tried. Then, while I am editing/expanding your comment, you  open an account on https://stackoverflow.com 
Once we have formulated the question, _you_ will _post_ the question on SO 
and I will make sure it has the correct tags/exposure so you get an _answer_. 
Having a good rating on SO is _essential_ to working as a developer.

**Comment by miguelmartins17** [comment]
This is the repository I found at the github.
I have to see the output of the application in order to understand if it is not incomplete.

https://github.com/kcarta/flutter-random-gif

**Comment by miguelmartins17** [comment]
@nelsonic The code didn't work for me. It doesn't show the gifs like it's loading.
I'll try to change a few things to see if I can make it work.

**Comment by nelsonic** [comment]
@miguelmartins17 I tried to run it on my `localhost` and got the following error:

```
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
/Users/n/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/f997e1c9b9354953b2226f6c368165b8/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.

/Users/n/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/f997e1c9b9354953b2226f6c368165b8/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         1.9s
Gradle task assembleDebug failed with exit code 1
```
Followed the instructions on https://flutter.dev/docs/development/androidx-migration

When I attempted to run **Refactor > Migrate to AndroidX** I see the following:
![image](https://user-images.githubusercontent.com/194400/74973852-241e3b80-541c-11ea-8f2a-e6b7ed89755a.png)

There wasn't anything to change in the project ... but it still didn't run. 🙄 

Then while reading [`/kcarta/flutter-random-gif/pubspec.yaml#L22`](https://github.com/kcarta/flutter-random-gif/blob/7b524c08c25581a7285d0a648d6fbcceabfdf23b/pubspec.yaml#L22)
we see that it is using a package called [`giphy_client`](https://pub.dev/packages/giphy_client) > https://github.com/brianegan/giphy_client
This looks like a promising avenue of exploration. 💡

**Comment by miguelmartins17** [comment]
**How can I push the files to GitHub except the one with the API key?**

I'm trying to push the code to the GitHub but I don't want to put the `file` that contains the `API key`, how can I push without pushing that file.
If I use `.` all the files go to Github.

**Comment by nelsonic** [comment]
@miguelmartins17 did you read [https://github.com/dwyl/learn-environment-variables](https://github.com/dwyl/learn-environment-variables#3-use-a-env-file-locally-which-you-can-gitignore) ? 
We use `.env` files in _most_ of our projects and safely add the `.env` file to `.gitignore`. 

The Dart/Flutter dotenv package: https://github.com/java-james/flutter_dotenv 
shows us that it's the same in Dart/Flutter. See: [`.gitignore#L74`](https://github.com/java-james/flutter_dotenv/blob/846cc93023c9092a2b2a91a80cc3cd2ab703d109/.gitignore#L74)

**Comment by miguelmartins17** [comment]
@nelsonic Thanks, so I'm gonna do that, and I'm gonna push it to the GitHub.

**Comment by nelsonic** [comment]
Closing as the code created is now out-of-date. 😞
