### ISSUE TITLE
Chore: Tidy up and Extend Learn Flutter Docs 📝 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#68]
The contents of this repo is "OK" as a starting point but it feels like it could use some "polish" / updating.

# Todo

+ [x] Read through the repo and update to make it more beginner-friendly
+ [x] Update any instructions & code samples as required
+ [x] Finish any in-progress examples 

# Tidy Up

+ [x] Review the open PRs: https://github.com/dwyl/learn-flutter/pulls

<img width="515" alt="image" src="https://user-images.githubusercontent.com/194400/200530900-145dc3a5-6de1-4652-9e1a-c025977099d0.png">

  + [x] Random GIF: https://github.com/dwyl/learn-flutter/pull/39
  + [x] How to use Environment Variables in a Flutter App: https://github.com/dwyl/learn-flutter/pull/41

+ [ ] Review what is useable on the branches: https://github.com/dwyl/learn-flutter/branches 
  + [ ] `DELETE` if no longer relevant

**Comment by nelsonic** [comment]
@LuchoTurtle's PR: https://github.com/dwyl/learn-flutter/pull/69 🎉

**Comment by nelsonic** [comment]
@LuchoTurtle to create a micro-PR to add GitHub Actions to this repo so that we can check everything is working. 🙏 
As per: https://github.com/dwyl/flutter-counter-example/pull/7#issuecomment-1316625719

**Comment by LuchoTurtle** [comment]
@nelsonic you should find it here -> https://github.com/dwyl/learn-flutter/pull/71

**Comment by nelsonic** [comment]
Thanks. Merged. Please confirm Working. 🤞

**Comment by LuchoTurtle** [comment]
Similarly to what happened in https://github.com/dwyl/flutter-counter-example/issues/6#issuecomment-1316782820, the CI should work when working with the latest Flutter version, as it's the case with #69 . After this PR is merged, it should work 😄

**Comment by nelsonic** [comment]
Gotcha. Thanks. 👌
