### ISSUE TITLE
`drift` reactive persistence library for `Flutter` & `Dart` built on top of `sqlite`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#70]
This looks like the persistence library we'll be using: [ please share alternatives if you've found any! ]

https://pub.dev/packages/drift  |  https://github.com/simolus3/drift  |  https://drift.simonbinder.eu

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/194400/200678959-5f0bf45c-4ff9-42a5-9649-75ba1a2724b3.png">

Looks like it's actively developed/maintained and has _many_ contributors/users. 
Has support for Web. 🕸️ 

> Originally shared by @th0mas 🧞 as **`MOOR`**: https://github.com/dwyl/flutter-todo-list-tutorial/issues/15 👌 

# Todo

+ [x] Follow the Getting Started guide: https://drift.simonbinder.eu/docs/getting-started/
  + [x] Sample Todo List app: https://github.com/simolus3/drift/tree/develop/examples/app
+ [x] Create a "**Hello World**" example storing some basic data on the device 
    e.g: "last viewed time" for the page so each time you refresh the page it displays: 
    + [x] _Current_ Date+Time 
    + [x] _Previous_ Date+Time
    + [x] _Difference_ between the two so you know how much time has passed. 
+ [x] Store **Todo List `items`** on the **Device** for offline-support see: https://github.com/dwyl/flutter-todo-list-tutorial/issues/18

Not putting a time estimate on this because want people to take a look and _discuss_ the work first. 💬 🙏

**Comment by nelsonic** [comment]
Ok. I trust your judgement. 👌 
Our objective is to have a simple/gentle intro to the topic. 👩‍💻 
If you feel it's covered, that's good. 🎉

**Comment by LuchoTurtle** [comment]
@nelsonic I feel like this should be marked as "completed", since it was addressed in https://github.com/dwyl/learn-flutter/issues/70#issuecomment-1329210602
