### ISSUE TITLE
Research: How to create a Progressive Web App (PWA) using `Flutter`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#80]
At present I am using the [**`MVP`**](https://mvp.fly.dev/) in `Safari` Desktop and Mobile on my Mac and iPhone respectively.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/194400/219393018-9850abcb-d1b7-4d08-a24a-c61a82c2b4e8.png">

It's an "OK" experience during `MVP` ... but we can do _much_ better even in the _short_-term. 

As we recently saw with **`Hoppscotch`**: [/dwyl/mvp/hoppscotch.md#hoppscotch-setup](https://github.com/dwyl/mvp/blob/eafe737642cced060eac9862c0b7b2c471d2909a/lib/api/hoppscotch.md#hoppscotch-setup)
The recommended approach to running their App is to "Install" it as a "Chrome" App:

![image](https://user-images.githubusercontent.com/194400/219343081-7c172895-7b7e-4f01-8fb5-66efa9d44e78.png)

Which is exactly how I run it on my `localhost`:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/194400/219316829-fbf77d8e-aee1-4613-ba0b-c35efbffb6ee.png">

It means that it runs full-screen and you can <kbd>command | alt</kbd>+<kbd>tab</tab> and immediately find it:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/194400/219342590-293242a8-b32d-4984-9adb-28401e5bb0c7.png">

6 Second Demo:
https://user-images.githubusercontent.com/194400/219318400-e5a14779-ccb3-479f-a8fc-73700323016a.mov

# Todo

+ [x] Research how to package a `Flutter App` as a `PWA` 🔍 e.g: https://blog.codemagic.io/pwa-in-flutter/
+ [ ] Create new file: `pwa.md` in _this_ repo and capture all the knowledge + steps required. 📝 
+ [ ] Add `PWA` capability to one of our _existing_ `Flutter` demo apps 📱 e.g: https://github.com/dwyl/flutter-phoenix-channels-demo

**Comment by nelsonic** [comment]
@LuchoTurtle do you want to take a look at this today?

**Comment by LuchoTurtle** [comment]
Sure 👍

**Comment by nelsonic** [comment]
@LuchoTurtle to answer your question regarding which of our Flutter Demo Apps should be enhanced with `PWA` capability, it would be cool to add it to one that demos something useful like https://github.com/dwyl/flutter-todo-list-tutorial but that appears to not be deployed anywhere so that's why I was suggesting the https://github.com/dwyl/flutter-phoenix-channels-demo which is on `Fly.io`: https://flutter-phoenix-channels-frontend.fly.dev/#/

Which I just checked: has a `PWA` option

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/194400/219610450-17f3ed51-8587-4126-84e3-7b7f497246e5.png">

"Installed" the same as `Hoppscotch`:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/194400/219611308-552a8ac7-c232-48d1-947f-350d49bf7649.png">


When I "install" it I get a full-screen:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/194400/219610649-46a154d8-9506-43b8-95b2-37a4cca6d8fd.png">

Demo screen recording:
https://user-images.githubusercontent.com/194400/219611430-5363cd72-1516-484f-8f60-08b2fdab9a2e.mov

But the `App` Logo is just the `Flutter` one: 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/194400/219611210-23568c9d-8eda-47c5-86d5-01c4fd3b78a0.png">

So it _appears_ as though just the act of deploying the `Flutter` App to `Fly.io` ("Web")
automagically added some basic `PWA` support!! 🎉 

So "all" we need to do is document how to update the `icon` and we can _already_ start adding `PWA` support to our `App` !! 🚀

**Comment by nelsonic** [comment]
So ... _some_ of the work for getting `PWA` support for our `App` is already done for us! 🙌 
We now need to figure out if there is extra work to enable it for a subdomain e.g: `app.dwyl.com`
And what format the `icon/logo` has to be to appear on `macOS` and `iOS` when the `Flutter` app is "installed".

Do you mind picking this up and documenting it in a `pwa.md` here in `learn-flutter`? 🙏

**Comment by LuchoTurtle** [comment]
This issue is addressed by these two PRs:

https://github.com/dwyl/learn-flutter/pull/81
https://github.com/dwyl/flutter-phoenix-channels-demo/pull/3

**Comment by nelsonic** [comment]
Remove the old version:

![uninstall-remove-app](https://user-images.githubusercontent.com/194400/219923513-153f5a97-ca5e-452b-8447-a023e213564f.png)

New version has updated logo:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/194400/219923554-c29fc067-a818-435f-9b33-771a135b995e.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/194400/219923681-891b8f51-547c-4b76-9ed3-88cca6a41a3e.png">

PWA working: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/194400/219924217-52bab2fc-62ef-44fc-9d57-a9da522406d5.png">
