### ISSUE TITLE
Feat: `i18n` in `Flutter` 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#90]
So far we have built all our `Flutter` demo apps in **`English`** 🇬🇧 
which is _fine_ for the [`1.5 Billion` people](https://www.statista.com/statistics/266808/the-most-spoken-languages-worldwide/) who speak it ... 💭 
But what about the other `6.2 Billion` i.e. **`85%`** of the **world** who **_don't_ speak `English`**...? 🤷‍♂️ 
We have people in our Team/Org (e.g: our Housekeeper and Foreman) who don't speak or read a _word_ of `English`. 😮 
To make our `App` _useful_ to them, we need to translate it to their language. 🇵🇹

# Todo

+ [ ] ***Either*** pick one of the _existing_ `Flutter` Apps https://github.com/dwyl?q=flutter 
e.g: [**`dwyl/flutter-todo-list-tutorial`**](https://github.com/dwyl/flutter-todo-list-tutorial) or [**`dwyl/flutter-bloc-tutorial`**](https://github.com/dwyl/flutter-bloc-tutorial)
and **_extend_ it** to have **at _least_ 2 languages** e.g. `EN`, `FR` & `PT`
***OR***
Create a `new` repo with an isolated demo/tutorial showcasing an `App` with multiple languages.

+ [ ] Document the steps so that a **_complete_ beginner** can follow them.
  + [ ] create a new file called `i18n.md` in this repo. 🆕 
  + [ ] populate the file with _everything_ you learned 📝 
  + [ ] Link to the file from the main `README.md` 🔗 
+ [ ] Write tests that include language switching. i.e: text in the interface will have changed

We will be implementing this in our `App` ASAP to make it _useful_ to the people we are _already_ working with. 
We want to translate _everything_ in it including placeholders and menus at the tap of a language icon. 

# Bonus Level!

+ [ ] Use `Google Translate` to translate the interface to a language that reverses the direction of text 
e.g. Right-to-left Script: [wikipedia.org/wiki/Right-to-left_script](https://en.wikipedia.org/wiki/Right-to-left_script) e.g: Arabic [wikipedia.org/wiki/Arabic_script](https://en.wikipedia.org/wiki/Arabic_script)
The person doing this task doesn't need to speak the language _personally_ ... 
just remember to do a _reverse_-translate and confirm the meaning isn't lost. 

> **Note**: `while` I don't expect this to take longer than `T1d` because it _appears_ to be well-documented in: 
https://docs.flutter.dev/development/accessibility-and-localization/internationalization
If it does end up taking a bit longer in practice, that's fine, just time-box it and leave regular comments on this issue.

**Comment by nelsonic** [comment]
@LuchoTurtle you've made a good demo of `i18n` in [https://github.com/dwyl/flutter-navigation-menu-demo/pull/5](https://github.com/dwyl/flutter-navigation-menu-demo/pull/5#issuecomment-1545414460) 🎉 
We need to document it _comprehensively_. 📝 
Please confirm you are happy to do this as your next task so that it's still fresh in your head. 🙏

**Comment by LuchoTurtle** [comment]
I think I've documented the process in https://github.com/dwyl/flutter-navigation-menu-demo/pull/5. Would it make sense to just refer to it from this document?
Or would you prefer I implement `i18n` [dwyl/flutter-todo-list-tutorial](https://github.com/dwyl/flutter-todo-list-tutorial) or [dwyl/flutter-bloc-tutorial](https://github.com/dwyl/flutter-bloc-tutorial) and document in the respective readme *and then* defer to it from the `learn-flutter` repo?

**Comment by nelsonic** [comment]
I think as long as we have _somewhere_ this is documented we can deep-link to it from the `learn-flutter/README.md` 👌 
We will need to set this up in the `App` next so the docs need to be Gucci. 😉

**Comment by LuchoTurtle** [comment]
@nelsonic should I deep link in the `learn-flutter` repo to this README to close this issue?

**Comment by nelsonic** [comment]
Yes, please. 🙏
