### ISSUE TITLE
Emojis 📱 😍 🙏 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#91]
`people` _expect_ to be able to use `Emoji`
Therefore we need to understand how to use `Emoji` in a `Flutter` App.

# Todo

+ [ ] investigate how to use `Emoji` in `Flutter`
  + [ ] Firstly does it render natively if we have an `emoji` in a bloc of text e.g. `Text()` widget?
  + [ ] Does a `Flutter` App natively support inputting `emoji`?

Once we've established the basics we can try more advanced things.
